name: talk_hub
description: "A demo application focused on real-time audio, video, and text chat using Flutter and Firebase technologies."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  # firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_ui_auth: ^1.16.0
  cloud_firestore: ^5.4.4

  # for google sign in
  google_sign_in: ^6.2.1
  # for fonts
  google_fonts: ^6.2.1
  # service locator
  get_it: ^8.0.0
  # Value equality
  equatable: ^2.0.5
  # Functional programming things
  dartz: ^0.10.1
  # to check internet connection
  internet_connection_checker: ^1.0.0+1
  # for state management
  flutter_bloc: ^8.1.6
  # for shimmer effect
  shimmer: ^3.0.0
  # for route management
  go_router: ^14.2.8
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
